name: newcity
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  # google_fonts: ^6.2.1
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_cli: ^1.8.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  dio: ^5.7.0
  retry: ^3.1.2
  permission_handler: ^11.3.1
  image_picker_platform_interface: ^2.10.0
  image: ^4.3.0
  get_storage: ^2.1.1
  path_provider: ^2.0.15
  path_provider_android: ^2.2.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/placeholder.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
